services:
  mystampa:
    image: mystampa-stampa
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mystampa
    restart: always
    ports:
      - "3032:3032"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./assets:/app/assets
      - mystampa_config:/app/data
    networks:
      - mysagra-network

volumes:
  mystampa_config:

networks:
  mysagra-network:
    external: true
